# Generated by Django 2.2.4 on 2020-05-08 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200507_2027'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingaddress',
            name='save_info',
            field=models.BooleanField(default=False),
        ),
    ]
