# Generated by Django 2.2.4 on 2020-05-08 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='/profile/shop_logo.png', upload_to='profile'),
        ),
    ]
